AllCops:
  CacheRootDirectory: tmp/rubocop_cache
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"
    - "lib/endpoint_security/generated/**/*"
    - "ext/endpoint_security/generated/**/*"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/GlobalVars:
  Exclude:
    - "ext/**/extconf.rb"

Style/StringLiteralsInInterpolation:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 50
