# frozen_string_literal: true

module EndpointSecurity
  module Codegen
    class EmitRuby
      def initialize(event_types_ir, cacheable: [])
        @ir = event_types_ir
        @cacheable = cacheable
      end

      def event_types
        constants = @ir.events.map { |event| "    #{event.symbol.upcase} = :#{event.symbol}" }.join("\n")
        pairs = @ir.events.map { |event| "      #{event.symbol}: #{event.value}" }.join(",\n")
        reserved = @ir.events.select(&:reserved).map { |event| ":#{event.symbol}" }.join(", ")
        cacheable = @cacheable.map { |event| ":#{event}" }.join(", ")

        <<~RUBY
          # frozen_string_literal: true

          # Generated by codegen/run.rb. Do not edit.

          module EndpointSecurity
            module EventType
          #{constants}
              LAST = #{@ir.last}
              SYMBOL_TO_VALUE = {
          #{pairs}
              }.freeze
              VALUE_TO_SYMBOL = SYMBOL_TO_VALUE.invert.freeze
              ALL = SYMBOL_TO_VALUE.keys.freeze
              ALL_AUTH = ALL.select { |event| event.to_s.start_with?("auth_") }.freeze
              ALL_NOTIFY = ALL.select { |event| event.to_s.start_with?("notify_") }.freeze
              RESERVED = [#{reserved}].freeze
              CACHEABLE = [#{cacheable}].freeze

              module_function

              def all = ALL
              def all_auth = ALL_AUTH
              def all_notify = ALL_NOTIFY
              def auth?(event) = event.to_s.start_with?("auth_")
              def notify?(event) = event.to_s.start_with?("notify_")
              def reserved?(event) = RESERVED.include?(event.to_sym)
              def cacheable?(event) = CACHEABLE.include?(event.to_sym)
              def flags_response?(event) = event.to_sym == :auth_open
              def value(event) = SYMBOL_TO_VALUE.fetch(event.to_sym)
              def symbol(value) = VALUE_TO_SYMBOL.fetch(value, value)
            end
          end
        RUBY
      end

      def availability
        pairs = @ir.events.map { |event| "      #{event.symbol}: \"#{event.minimum_os}\"" }.join(",\n")
        <<~RUBY
          # frozen_string_literal: true

          # Generated by codegen/run.rb. Do not edit.

          module EndpointSecurity
            module Availability
              EVENT_MIN_OS = {
          #{pairs}
              }.freeze
            end
          end
        RUBY
      end
    end
  end
end
