# frozen_string_literal: true

module EndpointSecurity
  module Codegen
    class EmitC
      def initialize(records, events)
        @records = records
        @events = events
      end

      def schema
        tables = @records.map do |record|
          next if record.fields.empty?

          fields = record.fields.map do |field|
            %(    {"#{field.name}", "#{field.type}", offsetof(#{record.name}, #{field.name}), #{field.minimum_version}})
          end.join(",\n")
          <<~C
            static const esrb_field_t fields_#{record.name}[] = {
            #{fields}
            };
          C
        end.join("\n")

        schemas = @records.map do |record|
          if record.fields.empty?
            %(    {"#{record.name}", NULL, 0})
          else
            table = "fields_#{record.name}"
            %(    {"#{record.name}", #{table}, sizeof(#{table}) / sizeof(#{table}[0])})
          end
        end.join(",\n")

        by_name = @records.to_h { |record| [record.name, record] }
        event_entries = @events.events.filter_map do |event|
          member = event.symbol.to_s.sub(/\A(?:auth|notify)_/, "")
          schema = "es_event_#{member}_t"
          next unless by_name.key?(schema)

          record = by_name.fetch("es_events_t", nil)
          field = record&.fields&.find { |candidate| candidate.name == member }
          next unless field

          indirect = field.type.include?("*") ? "true" : "false"
          %(    {#{event.value}, offsetof(es_events_t, #{member}), "#{schema}", sizeof(#{schema}), #{indirect}})
        end.join(",\n")

        <<~C
          /* es_schema.c -- generated by codegen/run.rb. Do not edit. */
          #include <EndpointSecurity/EndpointSecurity.h>
          #include <stddef.h>
          #include "field.h"

          #{tables}
          const esrb_schema_t esrb_schemas[] = {
          #{schemas}
          };
          const size_t esrb_schema_count = sizeof(esrb_schemas) / sizeof(esrb_schemas[0]);

          const esrb_event_schema_t esrb_event_schemas[] = {
          #{event_entries}
          };
          const size_t esrb_event_schema_count = sizeof(esrb_event_schemas) / sizeof(esrb_event_schemas[0]);
        C
      end
    end
  end
end
