# frozen_string_literal: true

module EndpointSecurity
  module Codegen
    class EmitRuby
      def initialize(event_types_ir, cacheable: [], enumerations: [])
        @ir = event_types_ir
        @cacheable = cacheable
        @enumerations = enumerations
      end

      def event_types
        constants = @ir.events.map do |event|
          "    # The +#{event.symbol}+ event.\n    #{event.symbol.upcase} = :#{event.symbol}"
        end.join("\n")
        pairs = @ir.events.map { |event| "      #{event.symbol}: #{event.value}" }.join(",\n")
        reserved = @ir.events.select(&:reserved).map { |event| ":#{event.symbol}" }.join(", ")
        cacheable = @cacheable.map { |event| ":#{event}" }.join(", ")

        <<~RUBY
          # frozen_string_literal: true

          # Generated by codegen/run.rb. Do not edit.

          module EndpointSecurity
            # Event names and numeric values from the build SDK.
            module EventType
          #{constants}
              # Exclusive upper bound for event enum values.
              LAST = #{@ir.last}
              # Event symbols keyed by their SDK enum values.
              SYMBOL_TO_VALUE = {
          #{pairs}
              }.freeze
              # SDK enum values keyed by event symbol.
              VALUE_TO_SYMBOL = SYMBOL_TO_VALUE.invert.freeze
              # All events known to the build SDK.
              ALL = SYMBOL_TO_VALUE.keys.freeze
              # All authorization events.
              ALL_AUTH = ALL.select { |event| event.to_s.start_with?("auth_") }.freeze
              # All notification events.
              ALL_NOTIFY = ALL.select { |event| event.to_s.start_with?("notify_") }.freeze
              # Undocumented reserved event slots.
              RESERVED = [#{reserved}].freeze
              # Events for which Endpoint Security accepts cached responses.
              CACHEABLE = [#{cacheable}].freeze

              module_function

              # @return [Array<Symbol>] all events
              def all = ALL
              # @return [Array<Symbol>] authorization events
              def all_auth = ALL_AUTH
              # @return [Array<Symbol>] notification events
              def all_notify = ALL_NOTIFY
              # @return [Boolean] whether +event+ is an authorization event
              def auth?(event) = event.to_s.start_with?("auth_")
              # @return [Boolean] whether +event+ is a notification event
              def notify?(event) = event.to_s.start_with?("notify_")
              # @return [Boolean] whether +event+ is an undocumented reserved slot
              def reserved?(event) = RESERVED.include?(event.to_sym)
              # @return [Boolean] whether +event+ accepts a cached response
              def cacheable?(event) = CACHEABLE.include?(event.to_sym)
              # @return [Boolean] whether +event+ uses a flags response
              def flags_response?(event) = event.to_sym == :auth_open
              # @return [Integer] SDK enum value for +event+
              def value(event) = SYMBOL_TO_VALUE.fetch(event.to_sym)
              # @return [Symbol, Integer] event symbol, or +value+ when unknown
              def symbol(value) = VALUE_TO_SYMBOL.fetch(value, value)
            end
          end
        RUBY
      end

      def enums
        tables = @enumerations.map do |enumeration|
          values = enumeration.values.map { |value| "        #{value.value} => :#{value.symbol}" }.join(",\n")
          <<~RUBY.chomp
              "#{enumeration.name}" => {
            #{values}
              }.freeze
          RUBY
        end.join(",\n")

        <<~RUBY
          # frozen_string_literal: true

          # Generated by codegen/run.rb. Do not edit.

          module EndpointSecurity
            # Symbol conversion for SDK enumeration fields.
            module Enum
              # Numeric-to-symbol tables keyed by SDK typedef name.
              TABLES = {
          #{tables}
              }.freeze

              module_function

              # Returns the symbolic enum value, preserving unknown numeric values.
              # @return [Symbol, Integer]
              def symbol(type, value) = TABLES.fetch(type, {}).fetch(value, value)
            end
          end
        RUBY
      end

      def availability
        pairs = @ir.events.map { |event| "      #{event.symbol}: \"#{event.minimum_os}\"" }.join(",\n")
        <<~RUBY
          # frozen_string_literal: true

          # Generated by codegen/run.rb. Do not edit.

          module EndpointSecurity
            # Runtime support metadata for SDK events.
            module Availability
              # Minimum macOS version keyed by event symbol.
              EVENT_MIN_OS = {
          #{pairs}
              }.freeze
            end
          end
        RUBY
      end
    end
  end
end
